# Jekyll configuration for GitHub Pages
# See https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site

# Site settings
url: "https://rxfcscybersolutions.com"
<<<<<<< HEAD
baseurl: "rxfce.github.io."
=======
baseurl: "https://rxfce.github.io/RXFCsCyberSolutions.com/"
>>>>>>> e44391ff22910143ba5332d1ea90cdbad1a57c65
title: "RXFC's Cyber Solutions"
description: "Your hub for innovative cybersecurity and technology solutions."

# Build settings
markdown: kramdown
theme: minima

# Exclude these files from the build
exclude:
  - site.yml
  - README.md
  - LICENSE

# Enable custom domain
# If using a CNAME file, GitHub Pages will use it automatically
